### ISSUE TITLE
3v fan?

### ISSUE THREAD

**Issue by Zyles** [KyleRoss/rpi-fan-controller#1]
Is there a way to get this to work with 3v fans?

I don't want my fans spinning 24/7.

My 5v slots are taken by USB extension boards.

**Comment by KyleRoss** [comment]
Yes, you could make it work with a 3v fan instead. I don't know how much would need to change in the wiring diagram besides the pin used off the top of my head. There is some additional information here:
https://raspberrypi.stackexchange.com/questions/63126/will-3-3v-gpio-work-for-a-fan-without-hurting-the-pi

Note that the script in this repo would need to change based on the pin being used.
